"""
Варианты написаний (RO/RU/EN/транслит) → канонический ключ на английском.

Подключается через canonical_team_key() в team_names.py.
"""
from __future__ import annotations

# mechanical_key → canonical_key (lowercase, без пробелов)
TEAM_ALIASES: dict[str, str] = {
    # France / Ivory Coast
    "frana": "france",
    "franta": "france",
    "frantsiya": "france",
    "franciya": "france",
    "franciyakot": "france",
    "franța": "france",
    "coastadefildes": "ivorycoast",
    "coastadefilde": "ivorycoast",
    "coastadefildei": "ivorycoast",
    "kotdivuar": "ivorycoast",
    "kotdivoire": "ivorycoast",
    "cotedivoire": "ivorycoast",
    "divuar": "ivorycoast",
    # UK / common RO
    "anglia": "england",
    "olanda": "netherlands",
    "danemarca": "denmark",
    "nouazeelanda": "newzealand",
    "nouazelanda": "newzealand",
    "alger": "algeria",
    "belgia": "belgium",
    "polonia": "poland",
    "luxemburg": "luxembourg",
    "italia": "italy",
    "romania": "romania",
    "taragalilor": "wales",
    "tariledejos": "netherlands",
    # Russia / Eastern
    "rusia": "russia",
    "rossiya": "russia",
    "rossiia": "russia",
    "russia": "russia",
    # Spain / Iraq / Syria
    "spania": "spain",
    "ispaniya": "spain",
    "spain": "spain",
    "irak": "iraq",
    "iraq": "iraq",
    "siriya": "syria",
    "syria": "syria",
    # Americas
    "meksika": "mexico",
    "mexic": "mexico",
    "mexico": "mexico",
    "columbia": "colombia",
    "colombia": "colombia",
    "brazilia": "brazil",
    "brazil": "brazil",
    "venezuela": "venezuela",
    "argentina": "argentina",
    "honduras": "honduras",
    "chile": "chile",
    "canada": "canada",
    "sua": "usa",
    "usa": "usa",
    # Europe
    "germania": "germany",
    "germany": "germany",
    "portugalia": "portugal",
    "portugal": "portugal",
    "ucraina": "ukraine",
    "ukraine": "ukraine",
    "ungaria": "hungary",
    "hungary": "hungary",
    "finlanda": "finland",
    "finland": "finland",
    "norvegia": "norway",
    "norway": "norway",
    "suedia": "sweden",
    "shvetsiya": "sweden",
    "sweden": "sweden",
    "grecia": "greece",
    "gretsiya": "greece",
    "greece": "greece",
    "slovacia": "slovakia",
    "slovakia": "slovakia",
    "sloveniya": "slovenia",
    "slovenia": "slovenia",
    "muntenegru": "montenegro",
    "montenegro": "montenegro",
    "moldova": "moldova",
    "bulgaria": "bulgaria",
    "belarus": "belarus",
    "chehiya": "czechia",
    "czechia": "czechia",
    "czechrepublic": "czechia",
    "gvatemala": "guatemala",
    "guatemala": "guatemala",
    "serbiya": "serbia",
    "serbia": "serbia",
    "kipr": "cyprus",
    "cyprus": "cyprus",
    "gvinea": "guinea",
    "guinea": "guinea",
    "severnayairlandiya": "northernireland",
    "northernireland": "northernireland",
    "andorra": "andorra",
    "lihtenshtein": "liechtenstein",
    "liechtenstein": "liechtenstein",
    "tadzhikistan": "tajikistan",
    "tajikistan": "tajikistan",
    "indiya": "india",
    "india": "india",
    "iordania": "jordan",
    "jordan": "jordan",
    "maroc": "morocco",
    "morocco": "morocco",
    "egipt": "egypt",
    "egypt": "egypt",
    "elvetia": "switzerland",
    "switzerland": "switzerland",
    "turcia": "turkey",
    "turkey": "turkey",
    "uzbekistan": "uzbekistan",
    "irlanda": "ireland",
    "ireland": "ireland",
    "tunisia": "tunisia",
    "nigeria": "nigeria",
    "australia": "australia",
    "belgium": "belgium",
    "denmark": "denmark",
    "england": "england",
    "france": "france",
    "ivorycoast": "ivorycoast",
    "netherlands": "netherlands",
    "newzealand": "newzealand",
    "poland": "poland",
    "luxembourg": "luxembourg",
    "drcongo": "drcongo",
    # Women's national (base country keys get "women" suffix in hook)
    "braziliyazhen": "brazilwomen",
    "braziliei": "brazilwomen",
    "brazilief": "brazilwomen",
    "dominikanazhen": "dominicanwomen",
    "republiciidominicanef": "dominicanwomen",
    "turtsiyazhen": "turkeywomen",
    "niderlandyzhen": "netherlandswomen",
    # Clubs / leagues
    "tsska": "cska",
    "cska": "cska",
    "uniks": "unics",
    "unics": "unics",
    "indianafiver": "indianafever",
    "indianafever": "indianafever",
    "atlantadrim": "atlantadream",
    "atlantadream": "atlantadream",
    # Tennis (abbreviated RU ↔ full latin)
    "arnaldim": "arnaldimatteo",
    "matteoarnaldi": "arnaldimatteo",
    "kobollif": "cobolliflavio",
    "flaviocobolli": "cobolliflavio",
    "menshikya": "mensikjakub",
    "jakubmensik": "mensikjakub",
    "zvereva": "zverevalexander",
    "alexanderzverev": "zverevalexander",
    "shnaiderd": "shnaiderdiana",
    "dianashnaider": "shnaiderdiana",
    "hvalinskam": "chwalinskamaja",
    "majachwalinska": "chwalinskamaja",
    "kostyukm": "kostyukmarta",
    "andreevam": "andreevamirra",
}
